#!/bin/sh


gen_define()
{
	name=$1
	val=$2

	echo "#define $name $val"
}

gen_define_str()
{
	name=$1
	val=$2

	echo "#define $name \"$val\""
}

path_app_core_efl=`rpm -ql app-core-efl | grep libappcore-efl | head -1`
addr_appcore_efl_main=`readelf -s ${path_app_core_efl} | \
		       grep appcore_efl_main | awk '{print "0x" $2}' | head -1`

PATH_LIBAPPCORE_EFL=`gen_define_str PATH_LIBAPPCORE_EFL $path_app_core_efl`
ADDR_APPCORE_EFL_MAIN=`gen_define ADDR_APPCORE_EFL_MAIN $addr_appcore_efl_main`


EPD_DEFINES="
$PATH_LIBAPPCORE_EFL
$ADDR_APPCORE_EFL_MAIN
"

cat << EOF
/*
 * Autogenerated header
 */

#ifndef __ELM_PROF_DATA__
#define __ELM_PROF_DATA__
${EPD_DEFINES}
#endif /* __ELM_PROF_DATA__ */
EOF

