#!/bin/sh

get_addr()
{
	name=$1

	addr=$(readelf -sW ${lib_file} | grep " $name$" | grep " FUNC " | awk '{print $2}')
	if [[ -z "$addr" ]]; then
		echo "ERROR: symbol '$name' not found" >&2
		exit 1
	fi

	echo 0x$addr
}

lib_file=`rpm -ql webkit2-efl-debuginfo | grep "libewebkit2.so.debug$" | head -1`

inspector_addr=$(get_addr ewk_context_inspector_server_start); [ $? -eq 0 ] || exit $?
willexecute_addr=$(get_addr _ZN3JSC16ProfileGenerator11willExecuteEPNS_9ExecStateERKNS_14CallIdentifierE); [ $? -eq 0 ] || exit $?
didexecute_addr=$(get_addr _ZN3JSC16ProfileGenerator10didExecuteEPNS_9ExecStateERKNS_14CallIdentifierE); [ $? -eq 0 ] || exit $?

cat << EOF
/*
 * Autogenerated header
 */

#ifndef WSI_PROF_H_
#define WSI_PROF_H_


static const unsigned long INSPECTOR_ADDR = ${inspector_addr};
static const unsigned long WILLEXECUTE_ADDR = ${willexecute_addr};
static const unsigned long DIDEXECUTE_ADDR = ${didexecute_addr};

#endif /* WSI_PROF_H_ */
EOF
