#!/bin/sh -x


gen_define()
{
	name=$1
	val=$2

	echo "#define $name $val"
}

gen_define_str()
{
	name=$1
	val=$2

	echo "#define $name \"$val\""
}

# get appcore_efl_main addr
path_app_core_efl=$(rpm -ql app-core-efl | grep libappcore-efl | head -1)
addr_appcore_efl_main=$(readelf -s ${path_app_core_efl} | grep appcore_efl_main | awk '{print "0x" $2}' | head -1)

# get dlopen@plt and dlsym@plt addrs
tmp=$(mktemp)
path_launchpad=$(rpm -ql launchpad | grep launchpad-loader | head -1)
su root -c "objdump -d --section=.plt $path_launchpad" | grep ">:"  > $tmp
addr_dlopen_plt=0x$(cat $tmp | grep " <dlopen@" | cut -f1 -d' ')
addr_dlsym_plt=0x$(cat $tmp | grep " <dlsym@" | cut -f1 -d' ')
rm $tmp

if [ -z "$path_app_core_efl" -o -z "$addr_appcore_efl_main" -o -z "$path_launchpad" -o -z "$addr_dlopen_plt" -o -z "$addr_dlsym_plt" ]; then
	exit 1
fi

PATH_LIBAPPCORE_EFL=$(gen_define_str PATH_LIBAPPCORE_EFL $path_app_core_efl)
ADDR_APPCORE_EFL_MAIN=$(gen_define ADDR_APPCORE_EFL_MAIN $addr_appcore_efl_main)

PATH_LAUNCHPAD=$(gen_define_str PATH_LAUNCHPAD $path_launchpad)
ADDR_DLOPEN_PLT_LPAD=$(gen_define ADDR_DLOPEN_PLT_LPAD $addr_dlopen_plt)
ADDR_DLSYM_PLT_LPAD=$(gen_define ADDR_DLSYM_PLT_LPAD $addr_dlsym_plt)


NSP_DEFINES="
$PATH_LIBAPPCORE_EFL
$ADDR_APPCORE_EFL_MAIN
$PATH_LAUNCHPAD
$ADDR_DLOPEN_PLT_LPAD
$ADDR_DLSYM_PLT_LPAD
"

cat << EOF
/*
 * Autogenerated header
 */

#ifndef __NSP_DATA_H__
#define __NSP_DATA_H__
${NSP_DEFINES}
#endif /* __NSP_DATA_H__ */
EOF
