#!/bin/bash

get_addr()
{
	name=$1

	addr=$(cat ${tmp} | grep " $name$" | awk '{print $2}')
	if [ -z "$addr" ]; then
		echo "ERROR: symbol '$name' not found" >&2
		exit 1
	fi

	echo 0x$addr
}

script_dir=$(readlink -f $0 | xargs dirname)
source $script_dir/dyn_vars

if [ "$__tizen_profile_name__" == "tv" ]; then
	webkit_package_name=webkit2-efl-tv
else
	webkit_package_name=webkit2-efl
fi
lib_file=$(rpm -ql ${webkit_package_name}-debuginfo | grep "/usr/lib/debug/usr/lib/libewebkit2.so.debug$" | head -1)
tmp=$(mktemp)

readelf -sW ${lib_file} | grep " FUNC " > ${tmp}

inspector_addr=$(get_addr 'ewk_\(context\|view\)_inspector_server_start');
willexecute_addr=$(get_addr _ZN3JSC16ProfileGenerator11willExecuteEPNS_9ExecStateERKNS_14CallIdentifierE);
didexecute_addr=$(get_addr _ZN3JSC16ProfileGenerator10didExecuteEPNS_9ExecStateERKNS_14CallIdentifierE);

rm ${tmp}

if [ -z "${inspector_addr}" -o -z "${willexecute_addr}" -o -z "${didexecute_addr}" ]; then
	exit 1
fi

cat << EOF
/*
 * Autogenerated header
 */

#ifndef WSI_PROF_H_
#define WSI_PROF_H_


static const unsigned long INSPECTOR_ADDR = ${inspector_addr};
static const unsigned long WILLEXECUTE_ADDR = ${willexecute_addr};
static const unsigned long DIDEXECUTE_ADDR = ${didexecute_addr};

#endif /* WSI_PROF_H_ */
EOF
