#!/bin/bash


gen_define()
{
	name=$1
	val=$2

	echo "#define $name $val"
}

gen_define_str()
{
	name=$1
	val=$2

	echo "#define $name \"$val\""
}

check_null_or_exit()
{
	name=$1
	val=${!1}
	src=$BASH_SOURCE
	line=$BASH_LINENO

	if [ -z "$val" ]; then
		echo "$src:$line ERROR: value '$name' is null" >&2
		exit 1
	fi
}

# get appcore_efl_main addr
path_app_core_efl=$(rpm -ql app-core-efl | grep libappcore-efl | head -1)
check_null_or_exit path_app_core_efl

addr_appcore_efl_main=$(parse_elf ${path_app_core_efl} -s appcore_efl_main)
check_null_or_exit addr_appcore_efl_main

# get dlopen@plt and dlsym@plt addrs
path_launchpad=$(rpm -ql launchpad | grep launchpad-loader | head -1)
path_launchpad=${path_launchpad:-$(rpm -ql launchpad | grep launchpad-process-pool | head -1)}
check_null_or_exit path_launchpad

tmp=$(mktemp)
addr_dlopen_plt=$(su root -c "parse_elf $path_launchpad -r dlopen")
addr_dlsym_plt=$(su root -c "parse_elf $path_launchpad -r dlsym")
rm $tmp

addr_dlopen_plt=${addr_dlopen_plt:-0}
addr_dlsym_plt=${addr_dlsym_plt:-0}


PATH_LIBAPPCORE_EFL=$(gen_define_str PATH_LIBAPPCORE_EFL $path_app_core_efl)
ADDR_APPCORE_EFL_MAIN=$(gen_define ADDR_APPCORE_EFL_MAIN 0x$addr_appcore_efl_main)

PATH_LAUNCHPAD=$(gen_define_str PATH_LAUNCHPAD $path_launchpad)
ADDR_DLOPEN_PLT_LPAD=$(gen_define ADDR_DLOPEN_PLT_LPAD 0x$addr_dlopen_plt)
ADDR_DLSYM_PLT_LPAD=$(gen_define ADDR_DLSYM_PLT_LPAD 0x$addr_dlsym_plt)


NSP_DEFINES="
$PATH_LIBAPPCORE_EFL
$ADDR_APPCORE_EFL_MAIN
$PATH_LAUNCHPAD
$ADDR_DLOPEN_PLT_LPAD
$ADDR_DLSYM_PLT_LPAD
"

cat << EOF
/*
 * Autogenerated header
 */

#ifndef __NSP_DATA_H__
#define __NSP_DATA_H__
${NSP_DEFINES}
#endif /* __NSP_DATA_H__ */
EOF
