#!/bin/bash
preload_library_name="libdl-2.13.so"
preload_library_path="/lib/"
preload_open_function="dlopen@@GLIBC"

output=$1

#c_output=$1

#function print_license()
#{
#    filename=$1
#    license=\
#"/********************************************************\n"\
#" * !!!!!!!!!!      Autogenerated header       !!!!!!!!!!\n"\
#" * !!!!!!!!!!      do not edit this file      !!!!!!!!!!\n"\
#" *\n"\
#" *  DA probe\n"\
#" *\n"\
#" * Copyright (c) 2000 - `date +%Y` Samsung Electronics Co., Ltd. All rights reserved.\n"\
#" *\n"\
#" * Contact:\n"\
#" *\n"\
#" * Vitaliy Cherepanov <v.cherepanov@samsung.com>\n"\
#" *\n"\
#" * This library is free software; you can redistribute it and/or modify it under\n"\
#" * the terms of the GNU Lesser General Public License as published by the\n"\
#" * Free Software Foundation; either version 2.1 of the License, or (at your option)\n"\
#" * any later version.\n"\
#" *\n"\
#" * This library is distributed in the hope that it will be useful, but WITHOUT ANY\n"\
#" * WARRANTY; without even the implied warranty of MERCHANTABILITY or\n"\
#" * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public\n"\
#" * License for more details.\n"\
#" *\n"\
#" * You should have received a copy of the GNU Lesser General Public License\n"\
#" * along with this library; if not, write to the Free Software Foundation, Inc., 51\n"\
#" * Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA\n"\
#" *\n"\
#" * Contributors:\n"\
#" * - Samsung RnD Institute Russia\n"\
#" *\n"\
#" */\n"
#
#    echo -e "$license" >> $filename
#}
#
#function print_include_guard_open()
#{
#    filename=$1
#    echo -e "#ifndef __LD_PRELOAD_H__" >> $filename
#    echo -e "#define __LD_PRELOAD_H__\n" >> $filename
#}
#
#function print_include_guard_close()
#{
#    filename=$1
#    echo -e "#endif /* __LD_PRELOAD_H__ */" >> $filename
#}

function print_header()
{
    filename=$1
    echo -e "# Preload\n"\
            "if [ -d /sys/kernel/debug/swap/preload/loader/ ] \n"\
            "then" >> $filename
}

function print_open_function()
{
    filename=$1
    addr=$2
    echo -e "    echo 0x$addr > /sys/kernel/debug/swap/preload/loader/loader_offset" >> $filename
}

#function print_close_function()
#{
#    filename=$1
#    addr=$2
#    echo -e "const unsigned long dlclose_addr = 0x$addr;\n" >> $filename
#}

function print_lib_name()
{
    filename=$1
    echo -e "    echo \"$preload_library_path$preload_library_name\" > /sys/kernel/debug/swap/preload/loader/loader_path" >> $filename
}

function print_post()
{
    filename=$1
    echo -e "fi" >> $filename
}
##################################
#       Script entry point       #
##################################

open_addr=$(readelf -sW $preload_library_path$preload_library_name | grep $preload_open_function | awk '{print $2}')

#print_license $c_output
#print_include_guard_open $c_output
print_header $output
print_lib_name $output
print_open_function $output $open_addr
print_post $output
#print_close_function $c_output $close_addr
#print_include_guard_close $c_output
